### ISSUE TITLE
Tween.js missing and other issues

### ISSUE THREAD

**Issue by Cypherous** [ccpgames/ccpwgl#10]
Hi there, the tween.js linked in the example files is missing, also when are you guys going to give us access to the other files needed to run things, specifically the .red .cube and .fx files linked in the examples, its all well and good running these things from the CCP CDN but it breaks functionality with chrome if you're using SSL so currently chrome users only get half a page when looking at the starmap i have up and running, any information about this would be appreciated, and if i've missed a download link for the files i've mentioned then please feel free to point me towards it so i can run this locally rather than from the CDN

**Comment by cppctamber** [comment]
This issue has been solved and can be closed.
