### ISSUE TITLE
Planet.isLoaded() always returns undefined

### ISSUE THREAD

**Issue by dertseha** [ccpgames/ccpwgl#12]
The method [Planet.isLoaded()](https://github.com/ccpgames/ccpwgl/blob/fbf01782fe6567467588ef291e47ae7652a43e42/src/ccpwgl.js#L857) always returns undefined.
It refers to "this.hightDirty", which is an undefined member. But the wrapped object, ccpwgl_int.EvePlanet, contains such a member.

Yet I don't think this is the proper way to check whether the planet is loaded - this member of EvePlanet is reset to false in [GetBatches()](https://github.com/ccpgames/ccpwgl/blob/fbf01782fe6567467588ef291e47ae7652a43e42/src/eve/EvePlanet.js#L150) at the render stage.

Since there is no onLoad parameter for scene.loadPlanet(), for now we have to assume a planet is immediately in "loaded" state after construction.

**Comment by filipppavlov** [comment]
fixed in 205ce269eb790ef5e1884a6785ee45c62f5f1385
