### ISSUE TITLE
Overlay effects not applied to animations

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/ccpwgl#128]
When aplying overlayEffect they are ony applied to one animation state (not necessarily the right one) when playing an animation, the overlayeffect does not change

**Comment by filipppavlov** [comment]
What is the res path for overlay effect you are using?

**Comment by snitchashor** [comment]
res:/dx9/model/effect/shieldhardening.red but its the same for shieldboosting armor hardening and repairing. None of them follows animations

**Comment by filipppavlov** [comment]
There is an animated version of that effect: res:/dx9/model/effect/shieldhardening_skinned.red. In general almost all overlay effects have an _skinned version that needs to be applied to animated ships.  Unfortunately there is no easy way to know when the ship is animated or not.

**Comment by cppctamber** [comment]
Would `object.wrappedObjects[0].animation.animations.length` not be sufficient?

**Comment by filipppavlov** [comment]
Not necessarily, but it should work in 99% of cases

**Comment by snitchashor** [comment]
I tried it, the problem is that during the shipLoad Callback the ship is not yet fully loaded and wrappedObjects[0].animation.animations.length is still 0

**Comment by cppctamber** [comment]
Use ```if ('isSkinned' in sof.hull[hullName] && sof.hull[hullName].isSkinned === 1)``` for sof ships, and the above for non-sof objects.

**Comment by snitchashor** [comment]
Adding the skinned overlays solves the issue. Checking animations.length has to be done after animations have fully loaded.
