### ISSUE TITLE
Starmap has duplicated stars

### ISSUE THREAD

**Issue by fuzzysteve** [ccpgames/ccpwgl#13]
Some stars appear in two different places. Such as Otosela

I've pulled the mapping between starid and solarsystemid out of the code, and I'm seeing the same solarsystemid appearing against multiple starids, with different coordinates.

This makes the starmap less than useful.

**Comment by filipppavlov** [comment]
That starmap code was just an experiment. Once we have universe data via CREST I will make a proper example using that data.
