### ISSUE TITLE
Wrapped Objects Query

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#130]
Do you know if there is a plan to have any future space objects that use multiple wrapped objects apart from Tech 3 cruisers? I'm considering creating a class just for Tech3 cruisers in my version of ccpwgl and removing the wrapped object arrays. This will simply things some what and I wanted to make sure I wasn't shooting myself in the foot :3

**Comment by filipppavlov** [comment]
We don't have any plans to add more modular ships at least in the near future.

**Comment by cppctamber** [comment]
\o/ Thanks!
