### ISSUE TITLE
SpaceObjectFactory parameter names

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#135]
The parameter `sof.race.booster.warpHalpColor` looks like a spelling mistake, should it perhaps be `warpHaloColor` ?

**Comment by cppctamber** [comment]
The parameters `noiseAmplitureEnd` & `noiseAmplitureStart` from `sof.race.booster` shape object may also be errors, likely to be 'noiseAmplitudeEnd' & 'noiseAmplitudeStart'

**Comment by filipppavlov** [comment]
It appears these misspellings are in client data, so I won't be able to change them easily, but thanks for finding them)
I'll change EveSOF.js to look for warpHalpColor instead of warpHaloColor though.

**Comment by cppctamber** [comment]
Thought they might be :)
Cheers.
