### ISSUE TITLE
RenderMode device.RM_DEPTH and DepthAreas

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#136]
Is there a reason why the `RM_DEPTH` rendermode is never accumulated, and `DepthAreas` rendered?
Wondering if it's something missing or it's for something that isn't webgl compatible.

**Comment by filipppavlov** [comment]
As far as I remember, these are used in a depth pre-pass on DirectX 9 when shader quality is set to "high". Since we don't support "high" quality we don't use them in webgl.

**Comment by cppctamber** [comment]
Thanks.
