### ISSUE TITLE
Outdated GL-Matrix Library

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#152]
Hi Filipp, do you have any plans to refactor to the latest GL-Matrix library? The newer versions have quite different argument layouts but a lot more functionality. If not, perhaps we could start extending the TW2 Parameters to start handling some of these functions and remove the reliance on other libraries *or* perhaps I could start updating current gl library? 

This could also help us to get rid of a few of those global functions lying around :)

**Comment by cppctamber** [comment]
I had some time so I started updating it, but I haven't tested it all yet: https://github.com/cppctamber/ccpwgl-glmatrix3/

**Comment by filipppavlov** [comment]
I always wanted to either upgrade that library of roll something of my own, but never got to doing anything about that. I'll take a look at your implementation.

**Comment by cppctamber** [comment]
I've made a glmatrix only version so you can ignore the other utils if need be, I haven't quite figured out how to do them yet :3
