### ISSUE TITLE
Booster and Killmark constant buffers

### ISSUE THREAD

**Issue by mattikuspathfinder** [ccpgames/ccpwgl#155]
It seems that the killmark and booster shaders both reference the same constant buffer value, and do different things with it. Using chrome's shader editor, the cb value in question seems to be cb4[0].x, which the booster uses as an intensity value, and the killmark shader uses as the number of killmarks to display.Assuming that the shaders are correct, perhaps a different constant buffer needs to be bound to each (rather than using the same per-object PS data for both booster and killmark draw calls?)

**Comment by cppctamber** [comment]
A current work around for the problem of the shared VS/PS ShipData[0] below:

```function EveShip()
{
    this._super.constructor.call(this);

    this.boosterGain = 1;
    this.boosters = null;
    this.turretSets = [];
    this.killmarks = 0;

    this._turretSetsLocatorInfo = [];
}

EveShip.prototype.GetBatches = function (mode, accumulator)
{
    this._perObjectData.perObjectVSData.Get('Shipdata')[0] = this.killmarks;
    this._perObjectData.perObjectPSData.Get('Shipdata')[0] = this.killmarks;
    this._super.GetBatches.call(this, mode, accumulator);

    if (this.lod > 1) {
        for (var i = 0; i < this.turretSets.length; ++i) {
            this.turretSets[i].GetBatches(mode, accumulator, this._perObjectData);
        }
    }
    else {
        for (var i = 0; i < this.turretSets.length; ++i) {
            if (this.turretSets[i].firingEffect) {
                this.turretSets[i].firingEffect.GetBatches(mode, accumulator, this._perObjectData);
            }
        }
    }
    if (this.boosters)
    {
        accumulator.Render();
        accumulator.Clear();
        this._perObjectData.perObjectVSData.Get('Shipdata')[0] = this.boosterGain;
        this._perObjectData.perObjectPSData.Get('Shipdata')[0] = this.boosterGain;
        this.boosters.GetBatches(mode, accumulator, this._perObjectData);
    }
};```

Thanks to Pathfinder for his hard work finding the issue! :3

**Comment by cppctamber** [comment]
Most of the frigates don't seem to work even though I can see they have kill mark data, and I'm not sure why...

**Comment by cppctamber** [comment]
I've identified that the PS Ship data is shared more than the above.
Boosters, Killmarks and Dust shaders ( from chaos, not the current quadv5 which doesn't support dust ) all share some of these values.

**Comment by filipppavlov** [comment]
I am currently looking into this thing. Will fix it with the next update, possibly tomorrow.

**Comment by filipppavlov** [comment]
Should be fixed. Check sof.html demo file

**Comment by cppctamber** [comment]
Thanks Filipp, beautiful :3
