### ISSUE TITLE
Default killmark textures

### ISSUE THREAD

**Issue by mattikuspathfinder** [ccpgames/ccpwgl#156]
Killmarks don't seem to work with CCP's killmark textures. As far as I can tell, the issue is that when the render state is set up, TEXTURE_WRAP_S/T are only set to REPEAT if there are mipmaps present, which is only the case if the texture is a power of 2 in each direction. CCP's killmark textures are 64x192, so no mipmaps, and the WRAP mode is set to CLAMP. This kills the killmarks.

**Comment by filipppavlov** [comment]
Should be fixed. Check sof.html demo file
