### ISSUE TITLE
Updating an object's transform doesn't update it's EveSpriteSets

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#179]
Updating an object's transform doesn't update it's `EveSpriteSet`s.

- Tested on Windows 10 64BIT
- Chrome `50.0.2661.102 m` and Firefox `46.0.1`
- Version: current`ccpwgl_int.js` git file

Example:
```
var ship = scene.loadShip('ab3_t1:amarrbase:amarr');
var tr = ship.getTransform();
mat4.translate(tr, [1000,1000,1000]);
ship.setTransform(tr);
// Ship is translated
// It's sprite sets are not
```

Out of curiosity (and because I can't find it myself) where/ how do `EveSpriteSet`s world matrices get updated?

**Comment by filipppavlov** [comment]
Hmm, it should inherit the transform from the parent through per-object data. I'll take a look

**Comment by cppctamber** [comment]
Issue fixed thanks.

**Comment by cppctamber** [comment]
Unfortunately looks like this is still an issues. Weirdly the ship I tested it with (the dominix) works fine, but nothing else seems to.
