### ISSUE TITLE
Resources are loaded using HTTP

### ISSUE THREAD

**Issue by roxlukas** [ccpgames/ccpwgl#18]
The new version of CCP WebGL is using HTTP protocol to retrieve resources: SOF data, ship models, shaders and textures. If the website using CCP WebGL was loaded using HTTPS, it will cause browser security errors in Chrome (resulting in blank screen), and security warnings in Firefox.

JS should either detect if the website was lodaded using HTTPS or HTTP (like google analytics do) and use the correct protocol when calling for resources, OR it could be hard-coded to use HTTPS, whichever is easier to implement.

**Comment by Regner** [comment]
I believe this issue can be closed since the merge of PR #19
