### ISSUE TITLE
EveCurveLineSet and animations

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#190]
There are a few functions in the `EveCurveLineSet` constructor that I am interested in using: `ChangeLineMultiColor` and  `ChangeLineAnimation` but they don't seem to do anything apart from changing the colour of the lines. Does anyone have any examples where the do anything similar to their names?

**Comment by filipppavlov** [comment]
The ChangeLineMultiColor function sets the second color for line segment and a fraction (from 0 to 1) where the primary color changes to this second color.
The ChangeLineAnimation function controls secondary texture ("OverlayTexMap" parameter) scrolling along the line segment.

**Comment by cppctamber** [comment]
Do you happen to have a working example of this, I am unable to get the scrolling to work.

**Comment by cppctamber** [comment]
There are a couple of errors still in this file which I've fixed elsewhere, I'll post a pull request later.
