### ISSUE TITLE
ViewportAdjustment

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#192]
Hi @filipppavlov,

I'm presently writing a viewport manager, and I noticed there was a per frame vertex property `ViewportAdjustment` and was wondering what it's purpose was and what it's properties were?.

```
// From EveSpaceScene
perFrameVS.Get('ViewportAdjustment');
    viewportAdj[0] = 1;
    viewportAdj[1] = 1;
    viewportAdj[2] = 1;
    viewportAdj[3] = 1;
```
![example](https://cloud.githubusercontent.com/assets/7591350/15983079/1e7c8118-2ff0-11e6-91c2-3c80db81bf59.png)

**Comment by filipppavlov** [comment]
As far as I remember it's only used for "high" shader quality (for sampling depth), but I'll double-check when I am at the office.

**Comment by filipppavlov** [comment]
Yes, it is only used for sampling depth, that's why it is not correctly populated in javascript code

**Comment by cppctamber** [comment]
Thanks.
