### ISSUE TITLE
Future of CCPWGL

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#197]
Below are some topics regarding the future of ccpwgl that I'd like to discuss. The following pull request has been created to support this discussion: https://github.com/ccpgames/ccpwgl/pull/196

Matrix Library
====
**Do we want to upgrade to a newer matrix library?**
----
The latest glMatrix library from [glMatrix.net](http://glmatrix.net/) (_a later version of the one used now_) has some performance benefits, a much more logical and consistent argument order (_the receiving object is almost always first_) vs the current ( _the receiving object is either the last or the first argument_), more functionality and optimizations.

_**Benefits:**_
- SIMD Support
- Faster calculations
- More functionality
- Some complicated calculations have been reduced to single functions
- `vec2` functions
- `vec4` functions separated from quaternion functions
- better naming conventions

_**Penalties:**_
- Slightly more verbose in some situations
- Requires refactoring of ccpwgl
- Requires testing

**Do we want to create and maintain our own library?**
----
While the latest glMatrix.net library has a lot of functionality it is lacking some basic scalar operations (_I have included these in the pull request in the file `ext.js`_) and it's focus excludes any functionality for things like bounding boxes, bounding spheres, ray casting and planes (_I have versions of these in testing presently_).

_**There is no need for any of this extra functionality for ccpwgl to work with the new library as it is.**_ _Refactoring and replacing the current library is all that would be required._

However, my proposal is:
- Create and maintain our own library based off the latest glMatrix.net library
- Extend scalar functionality (_without creating a new file with those extensions as seen in my pull request_)
- Keep it separate from any ccpwgl files (_as we have now_)
- Keep the different math categories in separate files
- Provide a grunt process to build this library
- Migrate all glMatrix and math functions that exist solely in ccpwgl_int to this library
- Incrementally add non-core functionality (_see list below_)

I'd like to start adding (or see others adding) useful generic 3d library methods to enable quality applications to be made with minimal effort. Raycasting, colour picking and physics would be at the top of that list :3

I do not see this library having to be upgraded often once implemented so maintenance should be low.

**Proposed Files and Folders**
```
/src/math

// base
/src/math/gl3.js - Generic

// core
/src/math/vec2.js - Vector 2
/src/math/vec3.js - Vector 3
/src/math/vec4.js - Vector 4
/src/math/quat.js - Quaternion
/src/math/mat3.js - Matrix 3x3
/src/math/mat4.js - Matrix 4x4

// extended
/src/math/clr.js - Colors
/src/math/box.js - Bounding Box
/src/math/sph.js - Bounding Sphere
/src/math/pln.js - Plane
/src/math/tri.js - Triangle/ Face
/src/math/ray.js - Ray casting

// build
/dist/ccpwgl_gl3.js - Unminified
/dist/ccpwgl_gl3.min.js - Minified
```

EMCAScript 6 / Typescript
----
A couple of months back I converted the ccpwgl_int files to ES6 and while I didn't initially see any benefits as it was a pain to keep up to date, it did make extending the library easier, removed the need for a build process (_apart from converting to ES5_), made things a little more readable and simplified some of the code.

Would anyone apart from myself benefit from moving to ES6 (_or to Typescript as some others have suggested_)? And more importantly, would @filipppavlov want to maintain the library in this format. :3
_I'd be willing to put in the hours to covert it again (and the 10k or so linting issues as well) but only if it was to become the standard version._ 

For the immediate future I propose that we introduce some build tasks to create versions of `ccpwgl_int` and the matrix library that support the ES6 `import` and `export` features. 
Included in the aforementioned pull request there is a working example of how this could work: `grunt es6`

**Proposed Files and Folders**
```
/dist/ccpwgl_int.es6
/dist/ccpwgl_gl3.es6
```

**Compiled Files**
----
Move all compiled files to `/dist/`.
Users of ccpwgl would only need this folder for ccpwgl to work.

**Comment by cppctamber** [comment]
Presently trying to decide on a format for the extended matrix methods, of which I have multiple versions. Any input would be appreciated.

Match the style of the glMatrix libraries
```
/**
 * Copies a box3 to another
 * @param {box3} out - Receiving box3
 * @param{box3} box - Box to copy
 * @returns {box3} out
 */
box3.copy= function (out, box)
{
    out[0] = box[0];
    out[1] = box[1];
    out[2] = box[2];
    out[3] = box[3];
    out[4] = box[4];
    out[5] = box[5];
    return out;
};

// example
var bbox = box3.fromValues(mesh.minBounds, mesh.maxBounds);
box3.addPoint(bbox, { 100, 100, 100 });
box3.toArrays(bbox, mesh.minBounds, mesh.maxBounds);

```

Helper functions only, matching ccpwgl's coding style
```
/**
 * Copies a bounding box's bounds
 * @param {vec3} outMin- Receiving min bounds
 * @param {vec3} outMax- Receiving max bounds
 * @param {vec3} boxMin - Min bounds to copy
 * @param {vec3} boxMax - Min bounds to copy
 */
box.clone = function (outMin, outMax, boxMin, boxMax)
{
    vec3.copy(outMin, boxMin);
    vec3.copy(outMax, boxMax);
};

// example
box.addPoint(mesh.minBounds, mesh.maxBounds, { 100, 100, 100 };
```

Bounding box as a Tw2Parameter
```
function Tw2BoxParameter(name, minBounds, maxBounds)
{
    this.name = name || '';
    this.min = vec3.fromValues(-Infinity, -Infinity, -Infinity);
    this.max = vec3.fromValues(Infinity, Infinity, Infinity);
    if (minBounds) vec3.copy(this.min, minBounds);
    if (maxBounds) vec3.copy(this.max, maxBounds);
};

Tw2BoxParameter.prototype.Copy = function(box)
{
    vec3.copy(this.min, box.min);
    vec3.copy(this.max, box.max);
};

// Example
var bbox = new Tw2BoxParameter('Example Box', mesh.minBounds, mesh.maxBounds);
bbox.addPoint({100,100,100});
bbox.toArrays(mesh.minBounds, mesh.maxBounds);
```

**Comment by Regner** [comment]
Any chance of getting an NPM package built and published? Would be really slick to see something like Travis CI building the repo and publishing it.

**Comment by cppctamber** [comment]
Here is a reference for the original es6 conversion I made in may, which doesn't take advantage of any es6 functions apart from `export`, `extends` and `Class`: https://github.com/cppctamber/ccpwgl-es6

Originally I wanted to break things up into modules, however because some constructors require access to all the ccpwgl_int files it resulted in a lot of 'import/ export' lines, so i reverted back to the same grunt setup as we have now, using concat. If we didn't use typescript it would work very similar to what we have now:

1. all files kept separate (*.es6)
2. grunt concat all ccpwgl_int es6 files into one: ccpwgl_int.es6 (Will work now in chrome)
3. grunt concat all glMatrix files into one: ccpwgl_gl3.es6 (Will work now in chrome) 
4. grunt babel task to convert concatted files to standard javascript: ccpwgl_int.js, ccpwgl_gl3.js
5. grunt uglify task the js files: ccpwgl_int.min.js, ccpwgl_gl3.min.js

If using TypeScript I believe there would only be two tasks (convert to js and uglify) as the concat stages wouldn't be required, but this would need to be confirmed.

**Comment by filipppavlov** [comment]
Sorry I didn't reply earlier - I was on vacation. 
I would really love to upgrade to the newer glMatrix version. I'd do this as a first step.

Regarding "extended" math library. Wouldn't it be cleaner to have it as a totally separate project (either extending glMatrix or providing side-by-side functions) and only pull built minified file. It would also help creating unit tests for it; I've noticed a few bugs in that ext.js file.

ES6: I wouldn't be comfortable with it right now. Maybe next year? :)

Regarding box.js: I'd call the object aabb3 rather than box3 as you may eventually want to add non axis-aligned boxes.

Tw2BoxParameter: we use parameters to pass data to shaders. How would you use this one?

Collidables: I didn't quite get this part. How would you use collidables? How collidables relate to geometry providers? What are these Tw2Geometry constructors?

**Comment by cppctamber** [comment]
> Sorry I didn't reply earlier - I was on vacation.
> I would really love to upgrade to the newer glMatrix version. I'd do this as a first step.
>
> Regarding "extended" math library. Wouldn't it be cleaner to have it as a totally separate project (either extending glMatrix or providing side-by-side functions) and only pull built minified file. It would also help creating unit tests for it; I've noticed a few bugs in that ext.js file.

That was just an example for you to look at, I've since fixed most of the bugs and have combined everything together.

 I've taken the latest glmatrix library, all but one of the glmatrix functions you made in ccpwgl, my own functions, and some THREE.js functions and put them all into one library which I'm almost finished with. 

Initially I was going to just extend the latest glmatrix library but I didn't like some of their method naming conventions so renamed a few of them, which may not be desirable for you or ccpwgl. As it is unlikely that I'll need to change any of them in a big way this was okay for me. 

I'll separate them from my ccpwgl-es6 testing git and put them here for you to look at in the next couple of hours: https://github.com/cppctamber/ccpwgl-gl3

**Comment by cppctamber** [comment]
> ES6: I wouldn't be comfortable with it right now. Maybe next year? :)

I'm quite far along with this now, and with some help from some #devfleet members its much easier to maintain/ compile that my previous versions

> Regarding box.js: I'd call the object aabb3 rather than box3 as you may eventually want to add non axis-aligned boxes.

They're not specific to Axis Aligned or Object Aligned, have a peek at the gl3 library to see what I mean.

> Tw2BoxParameter: we use parameters to pass data to shaders. How would you use this one?

I found a better way for what I was describing there now and so the only extra Tw2 parameter I am using now is `Tw2QuanternionParameter` which is pretty much `Tw2Vector4Parameter` but with some extra methods.

> Collidables: I didn't quite get this part. How would you use collidables? How collidables relate to geometry providers? What are these Tw2Geometry constructors?

I was trying to make a system similar to `GetBatches` which would give users a generic way of doing ray Intersection and picking but have since started added ray `Intersect` methods to all EveObjects, EveSets/EveSetItems, `Tw2GeometryMesh` and `Tw2GeometryMeshArea` instead. 

Probably better to discuss the above in #ccpwgl on slack some time. :3

**Comment by cppctamber** [comment]
I've uploaded the gl3 version that I've been using to https://github.com/cppctamber/ccpwgl-gl3 , which you can install locally with npm `install ccpwgl-es6`
