### ISSUE TITLE
Curve Interpolation and Extrapolation Types

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#205]
Could we get a map of the interpolation and extrapolation types for Tw2 Curves please?

Thanks. :3

**Comment by filipppavlov** [comment]
Which ones? As you've probably noticed our curve system is a mess)

**Comment by cppctamber** [comment]
Mmmm, I was hoping for all of them! :) lol

**Comment by filipppavlov** [comment]
I've added constants for them to each curve in https://github.com/ccpgames/ccpwgl/commit/b96f144769b390728dd3b4836363fb1c305c1b99
Let me know if this helps.

**Comment by cppctamber** [comment]
This is amazing :P Thanks @filipppavlov +1
