### ISSUE TITLE
Invisible Eve Sets in objects created with the EveSOF

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#212]
I noticed there are quite a few Eve Sets (Sprites, Spotlights, Planes etc) in some objects created with the `EveSOF` constructor that aren't visible; either due to their colour settings, their scale, or both.

A good example to look at would be `gb2_t1:gallentebase:gallente` which has police sprites and some hangars that are all invisible: Example data: http://pastebin.com/fgbcuaq5 (search for "police" and "hangar")

I'm assuming this is unintentional, but wanted to make sure before I went and "fixed" it :3

**Comment by cppctamber** [comment]
CCP Pointy Bits has confirmed this sometimes happens in game also. Not sure if relevant.

**Comment by filipppavlov** [comment]
Yes, apparently this does happen in the client as well (I've checked gb2 and it has those black blinkies). I'll pass this on to our artists to take a look.

**Comment by cppctamber** [comment]
I was doing some ray-cast tests and I kept hitting things I couldn't see and thought It was a bug on my side lol! Thanks for the reply.
