### ISSUE TITLE
World Matrix

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#247]
Hi Fillip,

I'm trying to scale everything in a scene down from `[1,1,1]` to `[0.001,0.001,0.001]`.

Is there a Tw2VariableStore autoregister variable or a per frame Tw2RawData value that I can set and pass to the shaders to acheive my goal? (The Tw2Device world matrix isn't used anywhere so doesn't affect anything)

Cheers

**Comment by filipppavlov** [comment]
Hi
No, there's no global scale, but depending on what you do you may be able to achieve this by putting scale into the view matrix.

**Comment by cppctamber** [comment]
Thanks, I tried this first but there were some unexpected results with sprites and spotlights.
While I was able to solve the sprites the spotlights seem to have occlusion issues, will keep at it though cheers. <3

**Comment by cppctamber** [comment]
sorted! <3 Just needed to scale the intensity of the spots relative to the world scale, and then force all spots to rebuild their buffers.
