### ISSUE TITLE
Running multiple canvases in on window

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/ccpwgl#253]
right now you need to edit a line in the ccpwgl_int and one in the ccpwgl file to run multiple canvases in one scene.

to get the benefits of a shared resManager you wouldnt want to use the solution i use, the problem is though that the Tw2Device is an instance instead of a constructor because a ton of other classes use the device without a reference but through using the exported instance.

anyone interested in a "fixed" version?

**Comment by cppctamber** [comment]
There are a few constructors that can have their dependencies to the instantiated `device` object removed by replacing their device references with `GL` and `CCP` enums. 

As you can't create textures and buffers on one context/device and use them on another, any constructor that was tied to a specific device would need to have it's device defined as one of it's properties - which would need to be set by `Tw2ObjectReader` and/or `Tw2ResMan` and/or `EveSOF` or by it's parent object.  

However, regardless of how it's done you'd still need to load the same resources for each device/context you have, so a single resource manager between the two may not be any better than what you are doing now.

**Comment by Robbilie** [comment]
i just want to point out that with a tiny mod to the dist ccpwgl_int or a "hack" aka extra script being loaded before ccpwgl_int you can easily spawn multiple canvases on one page since you can generate multiple ccpwgl_int contexts

**Comment by cppctamber** [comment]
@Robbilie whats the extra script?

**Comment by Robbilie** [comment]
```
window.define = function (a, ccpwgl_int) {
	window.ccpwgl_int = ccpwgl_int;
};
window.define.amd = {};
```

**Comment by cppctamber** [comment]
Your solution is the easiest "fix", I can't see any other way of solving this presently.

This issue can be closed.
