### ISSUE TITLE
The resource file 'res:/dx9/model/station/soe/soes1/soes1.red' doesn't load and results in errors

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#27]
Loading the SOE station 'res:/dx9/model/station/soe/soes1/soes1.red' that was mentioned in the last ccpwgl_int.js file update doesn't load and results in the following error on Chrome and Canary:

`WebGL: INVALID_ENUM: drawElements: invalid type`

**Comment by filipppavlov** [comment]
We try to use a webgl extension for 32 bit index buffers for objects requiring more than 65536 vertices (https://www.khronos.org/registry/webgl/extensions/OES_element_index_uint/). SOES1 seems to be one of them. I would imagine this extension is available on most desktop machines. What is the OS on your machine?

**Comment by cppctamber** [comment]
Windows 8 64bit

**Comment by cppctamber** [comment]
`this.gl.getExtension("OES_element_index_uint")` is missing from the Tw2Device function (Thanks @aurora). Once this is called the model will load although I get the following errors:

- Error: WebGL: drawElements: bound element array buffer is too small for given count and offset
- Missing Normals on the Station Glass.

**Comment by filipppavlov** [comment]
This should be fixed with the latest commit.
