### ISSUE TITLE
Decal Planes on Space Object Animation

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#33]
When changing the animation state of a space object (eg. Blackbird/ cc4_t1), decal plane geometry on the animated parts of the ship stays static during the animation.

![example_decal_unanimated](https://cloud.githubusercontent.com/assets/7591350/8719296/b8ebd470-2bfe-11e5-9496-797e20f27bc6.jpg)

**Comment by filipppavlov** [comment]
fixed in 205ce269eb790ef5e1884a6785ee45c62f5f1385
