### ISSUE TITLE
Planet textures - Inheriting texture elements from other objects

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#41]
Planets sometimes 'inherit' texture elements from other objects during initial load.
Increasing the amount of non-ship space objects in a scene seems to have an effect on the the chances of this happening.

![planettexturederp](https://cloud.githubusercontent.com/assets/7591350/8761725/45fe3f2c-2db4-11e5-8883-0c9fe68055aa.jpg)

**Comment by cppctamber** [comment]
This bug can be recreated by loading a planet along with the following jumpgate: "res:/dx9/model/jumpgate/minmatar/msmg/msmg.red"

**Comment by filipppavlov** [comment]
I honestly don't know how to best fix this. I made some changes to the planet so that it loads faster, maybe that would at least make the issue less pronounced.

**Comment by cppctamber** [comment]
Thank you, it is much less pronounced <3
