### ISSUE TITLE
Galatea SpaceObjectFactory & Hecate Model

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#44]
Hi Filipp,

Would it be possible to get the latest version of the SOF data.red file and the Hecate Model please?

Cheers. 
<3

**Comment by ShioR** [comment]
Imp and Fiend too please!

<3

**Comment by filipppavlov** [comment]
I'll try to get Galatea resources next Friday.

**Comment by cppctamber** [comment]
Hi Filipp, perhaps we can hold out a little longer until the PBR stations and T3 come out on september the 29th :P
