### ISSUE TITLE
Planetary Bodies - Issues with Depth

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#45]
Spaceobjects get clipped/ intersected by planetary bodies when the camera distance gets to a certain point (I am unsure what amount) even though they are positioned in a scene where they shouldn't.

**Comment by cppctamber** [comment]
![image](https://cloud.githubusercontent.com/assets/7591350/9876384/e8ede114-5c09-11e5-8acb-a131d22571bb.png)

![image](https://cloud.githubusercontent.com/assets/7591350/9876418/1820f20a-5c0a-11e5-825b-05ae8b7bff78.png)

![image](https://cloud.githubusercontent.com/assets/7591350/9876450/3c821c50-5c0a-11e5-8746-19570a45d85f.png)

![image](https://cloud.githubusercontent.com/assets/7591350/9876288/09837a34-5c09-11e5-98e4-5f3142110728.png)

**Comment by filipppavlov** [comment]
Can you provide some setup script for the problem?

**Comment by cppctamber** [comment]
@filipppavlov I've not been able to recreate, you may have fixed it since I published this issue. If I am able to recreate it at a later time I will resubmit the issue then with example script.
