### ISSUE TITLE
Designer skins support + graphicMaterialSets.yaml

### ISSUE THREAD

**Issue by roxlukas** [ccpgames/ccpwgl#53]
There is no way to load designer skins such as **Raata Sunset** or **Blue Tiger** currently, because they cannot be described by ship DNA.

Right now to load the default skin I can use data from **graphicIDs.yaml** for a specific typeID:

sofHullName, sofRaceName, sofFactionName

Available shaders for a specific **sofRaceName** can be found by `SELECT DISTINCT sofFactionName FROM graphicIDs WHERE sofRaceName = [ships sofRaceName]`

Available in-game SKINs for specific typeID can be found via **skins.yaml, skinMaterials.yaml** and **graphicMaterialSets.yaml** (the last one is not part of the SDE yet, it contains sofFactionName).

Once all three variables are found, ship can be loaded in CCPWebGL:

`ship = scene.loadShip(sofHullName+':'+sofFactionName+':'+sofRaceName, undefined);`

PS. Including **graphicMaterialSets.yaml** in SDE would be nice too :-)

**Comment by cppctamber** [comment]
`sof.materials` is not currently in the `spaceObjectFactory/data.red` file which is required for this to work. Please include in the next update if possible <3

**Comment by filipppavlov** [comment]
As of latest update SOF can handle skins. Also there is a file res:/staticdata/skins.json containing SOF suffixes for skins in the game. To create a ship with a skin you append the suffix from skins.json to SOF path and pass that to scene.loadShip
