### ISSUE TITLE
res:/graphics/starmap/starmap.wbg & StarMap.js 

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#55]
The StarMap.js demo no longer works.
The starmap geometry file is reporting the following error:
`Tw2StaticEmitter:  input geometry res ' res:/graphics/starmap/starmap.wbg ' mesh lacks ( 0 ,  0 ) element required by particle system`

**Comment by filipppavlov** [comment]
I'll take a look at re-doing the map properly. Hopefully with the next update.
