### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#62]
Hi Fillip, is there a forum or communications channel we can all discuss development of ccpwgl outside of GitHub? - Cheers

**Comment by filipppavlov** [comment]
Hi
I didn't find any special place on eveonline forum. I'll ask IT guys if they can help us with that.

**Comment by cppctamber** [comment]
We could always make a channel on slack :3

**Comment by cppctamber** [comment]
A channel has been made on the tweetfleet slack #ccpwgl where we can discuss further if you like.
Thanks @aurora

**Comment by cppctamber** [comment]
To get a Tweetfleet slack invite visit https://www.fuzzwork.co.uk/tweetfleet-slack-invites/ and then join #ccpwgl and #devfleet
