### ISSUE TITLE
EveCurveLineSet

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#66]
EveCurveLineSet Lines not showing correctly when a spaceObject is removed from scene
- Lines show a black outline
- Line segment connection points are missing
- When resource purging occurs the line sprite texture is unloaded from memory resulting in completely black lines

-- With Connection Points (And Ship)
![image](https://cloud.githubusercontent.com/assets/7591350/12026091/631ee822-ae1a-11e5-9b3a-cd549aff28c3.png)

-- Without Connection Points (Ship Removed)
![image](https://cloud.githubusercontent.com/assets/7591350/12026070/31cbe84c-ae1a-11e5-9452-c697461a2fd6.png)

-- After Resource Clear
![image](https://cloud.githubusercontent.com/assets/7591350/12026078/4378ed92-ae1a-11e5-8c34-8f57cd640938.png)

**Comment by filipppavlov** [comment]
Rendering this this is a bit more involved. Here's a sample code:

var curveSet = new ccpwgl_int.EveCurveLineSet();
curveSet.lineEffect.parameters['TexMap'] = new ccpwgl_int.Tw2TextureParameter('TexMap', 'res:/texture/global/white.dds.0.png');
curveSet.lineEffect.parameters['OverlayTexMap'] = new ccpwgl_int.Tw2TextureParameter('OverlayTexMap', 'res:/texture/global/white.dds.0.png');
curveSet.lineEffect.Initialize();
var batches = new ccpwgl_int.Tw2BatchAccumulator();
ccpwgl.onPostSceneRender = function (dt) {
    curveSet.GetBatches(ccpwgl_int.device.RM_TRANSPARENT, batches);
    batches.Render();
    batches.Clear();
};
curveSet.AddCurvedLineCrt([1000, 1000, 1000], [1, 1, 1, 1], [-5000, -1050, 300], [1, 1, 1, 1], [1200, -4100, 2100], 10);
curveSet.AddStraightLine([-5000, -1050, 300], [0, 1, 0, 1], [1000, 1000, 1000], [0, 1, 0, 1], 10);
curveSet.SubmitChanges();

**Comment by cppctamber** [comment]
Perfect thanks Filipp.
