### ISSUE TITLE
T3 Cruisers Problem with Boosters and Turrets

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/ccpwgl#68]
When building a T3 cruiser using loadShip and the 5 resPaths, I does show up without boosters. Also simply loading Boosters does not work. The Boosters have no _boosterTransforms. When adding Boosters through EveBoosterSet.Add() providing the locators followed by a Rebuild they have been added once per Subsystem. e.g. a Legion with 6 booster locators in total coming from 2 different subsystems will have 6 _boosterTransforms for each of the 5 Subsystems. I think the same happens when mounting turrets with mountTurret() it looks like also every Turret is actually an overlay of five.

**Comment by snitchashor** [comment]
Edit: The problem with mountTurrets can be circumvented by mounting Turrets after all five subsystems have been loaded. This does not work for boosters though.

**Comment by cppctamber** [comment]
Could you share some example code which recreates this problem?

**Comment by cppctamber** [comment]
Couple of things for your information: Boosters have never worked for tech 3 ships assembled from multiple .red files, .red files for boosters are difficult to find, and the version of the spaceObjectFactory that ccpwgl uses doesn't include tech 3 ships :( :( :( 

```
ccpwgl.getSofData( function(obj){ sof = obj}); 


        /**
         * Creates boosters for ship loaded from .red files, and sets them up as per the supplied sof.race object
         * @param ship - A ship loaded via .red files (and not via the space object factory)
         * @param race - A Space Object Factory race object (ie. sof.race.gallente)
         */
        function createSofBoostersForNonSofShip(ship, race)
        {
            if (!ship.isLoaded() || !race) return;

            function _get(obj, property, defaultValue) {
                if (property in obj) {
                    return obj[property];
                }
                return defaultValue;
            }

            function _assignIfExists(dest, src, attr) {
                if (attr in src) {
                    dest[attr] = src[attr];
                }
            }

            function SetupBoosters(wrappedObject, hull, race)
            {
                var booster = new ccpwgl_int.EveBoosterSet();
                var hullBooster = hull['booster'];
                var raceBooster = _get(race, 'booster', {});
                _assignIfExists(booster, raceBooster, 'glowScale');
                _assignIfExists(booster, raceBooster, 'glowColor');
                _assignIfExists(booster, raceBooster, 'symHaloScale');
                _assignIfExists(booster, raceBooster, 'haloScaleX');
                _assignIfExists(booster, raceBooster, 'haloScaleY');
                _assignIfExists(booster, raceBooster, 'haloColor');
                booster.effect = new ccpwgl_int.Tw2Effect();
                booster.effect.effectFilePath = 'res:/Graphics/Effect/Managed/Space/Booster/Booster.fx';
                booster.effect.parameters['Color'] = new ccpwgl_int.Tw2Vector4Parameter('Color', _get(raceBooster, 'color', [0, 0, 0, 0]));
                booster.effect.parameters['BoosterScale'] = new ccpwgl_int.Tw2Vector4Parameter('BoosterScale', _get(raceBooster, 'scale', [1, 1, 1, 1]));
                booster.effect.parameters['WaveMap'] = new ccpwgl_int.Tw2TextureParameter('WaveMap', 'res:/Texture/Sprite/waveHiFi.dds.0.png');
                booster.effect.parameters['DiffuseMap'] = new ccpwgl_int.Tw2TextureParameter('DiffuseMap', raceBooster['textureResPath']);
                booster.effect.Initialize();
                booster.glows = new ccpwgl_int.EveSpriteSet();
                booster.glows.effect = new ccpwgl_int.Tw2Effect();
                booster.glows.effect.effectFilePath = 'res:/Graphics/Effect/Managed/Space/Booster/BoosterGlow.fx';
                booster.glows.effect.parameters['DiffuseMap'] = new ccpwgl_int.Tw2TextureParameter('DiffuseMap', 'res:/Texture/Particle/whitesharp.dds.0.png');
                booster.glows.effect.Initialize();
                booster.Initialize();
                wrappedObject.boosters = booster;
            }

            // Cycle through all the wrapped objects in a ship and build our boosters
            ship.wrappedObjects.forEach(function (item) {
                var fakeSofHull = {booster: {items: []}};
                for (var i = 0; i < item.locators.length; i++) {
                    if (item.locators[i].name.search("locator_booster") != -1) {
                        fakeSofHull.booster.items.push({
                            transform: item.locators[i].transform
                        })
                    }
                }
                SetupBoosters(item, fakeSofHull, race);
            });
        }
```

**Comment by snitchashor** [comment]
Thanks a lot, that worked like a charm.
The problem with turrets can be easily reproduced by loading a ship with the 5 subsys files and mountTurrets right after that. When you put the debug statements you can see that turrets are added after each subsystem is loaded, for all subsystems that are loaded at this point, so a few ones get rendered multiple times.

**Comment by cppctamber** [comment]
Join me in the tweetfleet slack #ccpwgl channel and I'll help you to debug the problem.
You can find the details on how to join in the #communications issue or in the tweet I sent you.

**Comment by snitchashor** [comment]
I applied to join, just takes a while I guess.

**Comment by filipppavlov** [comment]
I updated ship loading code to properly rebuild boosters once the ship is loaded. I'd recommend loading boosters from .red files instead of building them from SOF for Tech3 ships. The files for 4 races are:
res:/dx9/model/ship/booster/booster_amarr.red
res:/dx9/model/ship/booster/booster_caldari.red
res:/dx9/model/ship/booster/booster_gallente.red
res:/dx9/model/ship/booster/booster_minmatar.red
So you should be able to:
var ship = scene.loadShip(parts);
ship.loadBoosters('res:/dx9/model/ship/booster/booster_amarr.red');
Loading from files is better as it makes the code a bit future proof. I'll be changing booster-related code for the next update (in a month) to support new boosters and it will break that create-from-sof code.
Also, Tech3 ships are still not in SOF and will not be there in the near future.

As for turrets, I could not reproduce the issue. Can you please provide the list of subsystems (and a race) and a turret slot that is causing a trouble.

**Comment by cppctamber** [comment]
Thanks Filipp. <3

**Comment by cppctamber** [comment]
I use objects for all space object components as I'm dealing with a lot of custom designs (including boosters) and it is easier to create an object than a .red file. I'll try to remember that not everyone does this.

**Comment by snitchashor** [comment]
Hi!

first of all to reproduce the turrets problem, the following code should be enough:
```
								var skin = 'amarrbase';
								var booster = 'amarr';
								var subsys = ["res:\/dx9\/Model\/Ship\/Amarr\/StrategicCruiser\/ASC1\/ASC1_T3_s2v3\/ASC1_T3_s2v3.red","res:\/dx9\/Model\/Ship\/Amarr\/StrategicCruiser\/ASC1\/ASC1_T3_s1v3\/ASC1_T3_s1v3.red","res:\/dx9\/Model\/Ship\/Amarr\/StrategicCruiser\/ASC1\/ASC1_T3_s5v2\/ASC1_T3_s5v2.red","res:\/dx9\/Model\/Ship\/Amarr\/StrategicCruiser\/ASC1\/ASC1_T3_s4v3\/ASC1_T3_s4v3.red","res:\/dx9\/Model\/Ship\/Amarr\/StrategicCruiser\/ASC1\/ASC1_T3_s3v1\/ASC1_T3_s3v1.red"];
								var turrets = ["res:\/dx9\/model\/Turret\/Energy\/Beam\/M\/beam_heavy_T2.red","res:\/dx9\/model\/Turret\/Energy\/Beam\/M\/beam_heavy_T2.red","res:\/dx9\/model\/Turret\/Energy\/Beam\/M\/beam_heavy_T2.red","res:\/dx9\/model\/Turret\/Energy\/Beam\/M\/beam_heavy_T2.red","res:\/dx9\/model\/Turret\/Energy\/Beam\/M\/beam_heavy_T2.red","res:\/dx9\/model\/Turret\/Energy\/Beam\/M\/beam_heavy_T2.red"];

if (subsys.length == 5) {
                ship = scene.loadShip(subsys, whenLoaded);
                ship.loadBoosters('res:/dx9/model/ship/booster/booster_'+booster+'.red');
                for (var i = 0; i < turrets.length; i++) {
                            // mounting turrets does not work here
                                ship.mountTurret(i+1, turrets[i]);
                }
            }
```
In this case you don't simply get the turrets but actually multiple ones overlayed. This can be esily seen if you animate them to INACTIVE because only one will get animated the overlayed ones stay as they are. 
Also in this example loading the boosters does not work with your code changes, am I doing something wrong here?
Another Issue with the turrets on T3s is the Color not matching the hull, might be a problem with MaterialSets on non SOF ships.

**Comment by filipppavlov** [comment]
With boosters is just me being stupid. Please get the latest ccpwgl.js. I'll try to look into turrets tomorrow.

**Comment by snitchashor** [comment]
Boosters working nicely now. I just browsed through a number of T3 killmails and stumbled over one subsystem that seems to cause problems: res:/dx9/Model/Ship/Amarr/StrategicCruiser/ASC1/ASC1_T3_s5v1/ASC1_T3_s5v1.red
It renders fine on its own but does not work contructing a t3.

**Comment by cppctamber** [comment]
The culprit is the below code, which loads the turrets for every subsystem when you've predefined the turrets. 

```
for (var i = 0; i < self.turrets.length; ++i)
{
    if (self.turrets[i])
    {
        doMountTurret(i, self.turrets[i].path, self.turrets[i].state, self.turrets[i].target);
    }
}
```

**Comment by cppctamber** [comment]
@snitchashor try this and see if it works:

```
var legion = scene.loadShip(
    [
        'res:/dx9/model/ship/amarr/strategiccruiser/asc1/asc1_t3_s1v1/asc1_t3_s1v1.red', 
        'res:/dx9/model/ship/amarr/strategiccruiser/asc1/asc1_t3_s2v1/asc1_t3_s2v1.red', 
        'res:/dx9/model/ship/amarr/strategiccruiser/asc1/asc1_t3_s3v1/asc1_t3_s3v1.red', 
        'res:/dx9/model/ship/amarr/strategiccruiser/asc1/asc1_t3_s4v1/asc1_t3_s4v1.red', 
        'res:/dx9/model/ship/amarr/strategiccruiser/asc1/asc1_t3_s5v1/asc1_t3_s5v1.red'
    , 
    undefined
);
```

![legion](https://cloud.githubusercontent.com/assets/7591350/12405334/ff8ad94e-bea7-11e5-9cba-c587e681a4f5.jpg)

**Comment by snitchashor** [comment]
Ok this is a weird one. The code you posted works. The s5v1 subsystem has to be in last position, for all others the order doesn't matter as it seems.
For me a simple sort() before loading the subsystem array fixes this.

**Comment by filipppavlov** [comment]
Indeed, there seems to be an error in ASC1_T3_s5v1 asset. Sorting by system allows to work around it.

**Comment by filipppavlov** [comment]
The latest commit should fix turret issues, both material and double turrets. It also adds sorting for parts.

**Comment by snitchashor** [comment]
Thanks, I'll give it a go!

I found one more issue with T3s (sorry...)
The getBoundingSphere method assumes only one wrappedObject. Heres a piece of code i use for calculating a radius and center for T3s. Its basically calculating the most outer point of every subsystem, adds them up, scales them, this should give the center and then calculates the distance of the most outer point of every subsystem to the new center and returns the largest as radius. I'm not entirely sure if this is fully correct (highschool math was long ago) but it gives reasonable results:
```
var center = vec3.create([0,0,0]);
var radius = 0;
for (i = 0; i < spaceObject.wrappedObjects.length; i++) {
    outer = vec3.create();
    vec3.scale(spaceObject.wrappedObjects[i].boundingSphereCenter, (vec3.length(spaceObject.wrappedObjects[i].boundingSphereCenter)+spaceObject.wrappedObjects[i].boundingSphereRadius)/vec3.length(spaceObject.wrappedObjects[i].boundingSphereCenter), outer);
    vec3.add(center, outer);
}
vec3.scale(center, 1/(spaceObject.wrappedObjects.length));
for (i = 0; i < spaceObject.wrappedObjects.length; i++) {
    toCenter = vec3.create();
    vec3.subtract(spaceObject.wrappedObjects[i].boundingSphereCenter, center, toCenter);
    if (vec3.length(toCenter) + spaceObject.wrappedObjects[i].boundingSphereRadius > radius) {
        radius = (vec3.length(toCenter) + spaceObject.wrappedObjects[i].boundingSphereRadius);
    }
}
```

**Comment by snitchashor** [comment]
Turrets and boosters nicely working now, thanks!
