### ISSUE TITLE
fragment shader does not compile on IE or Edge

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/ccpwgl#70]
The latest version does not work for Internet Explorer or Edge:
```
Tw2EffectRes:  error compiling  fragment  shader (effect ' res:/graphics/effect.gles2/managed/space/spaceobject/v5/quad/quadv5.sm_hi '):  Shader compilation errors
(17, 6): syntax error, unexpected IDENT_TOK

Tw2EffectRes:  error compiling  fragment  shader (effect ' res:/graphics/effect.gles2/managed/space/spaceobject/v5/quad/quadheatv5.sm_hi '):  Shader compilation errors
(17, 6): syntax error, unexpected IDENT_TOK

Tw2EffectRes:  error compiling  fragment  shader (effect ' res:/graphics/effect.gles2/managed/space/decals/v3/decalnormalv3.sm_hi '):  Shader compilation errors
(17, 6): syntax error, unexpected IDENT_TOK
```
this one did work partially: https://github.com/ccpgames/ccpwgl/commit/205ce269eb790ef5e1884a6785ee45c62f5f1385

**Comment by filipppavlov** [comment]
We currently don't support IE and Edge. There used to be some serious problems with IE WebGL support before. I will see if anything has changed the next time I update resources.

**Comment by snitchashor** [comment]
Thanks for the heads up, i think recent IE 11 versions and Edge should fullfill most specifications. Performance isn't gonna be great on IE11 but there should be improvements in Edge. I would help but honestly trying to figure out why the shaders do not compile i got nothing more than that error message i posted also webgl-debug didn't give any hints.
