### ISSUE TITLE
Provide build system for combined & minified files, module structure

### ISSUE THREAD

**Issue by dertseha** [ccpgames/ccpwgl#8]
The repository currently only contains the dedicated source files and a minified result. Please provide a description and/or commands to create the combined files as well as the minified version for testing and to be able to reproduce it.

As a side request, it would be great if the whole thing was set up to be used with [require.js](http://requirejs.org/) / [browserify](http://browserify.org/) in an AMD like structure.
Would you accept a pull request with the whole thing reworked using requirejs?

**Comment by Regner** [comment]
This is fixed in PR #26
