### ISSUE TITLE
Phoenix (cdn1_t1) gives distorted turrets

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/ccpwgl#90]
When mounting turrets (doesn't matter which ones) on a Phoenix (cdn1_t1) the turrets become completely distorted.
![untitled](https://cloud.githubusercontent.com/assets/15797648/12510632/a2c9aac6-c10b-11e5-8ae1-65f3211984a8.jpg)

**Comment by filipppavlov** [comment]
Should be fixed in the latest update
